// ==========================================
// LISTE DES PAYS DE DESTINATION
// ==========================================
export const COUNTRIES: string[] = [
    'Allemagne',
    'Australie',
    'Autriche',
    'Belgique',
    'Brésil',
    'Canada',
    'Chine',
    'Corée du Sud',
    'Danemark',
    'Égypte',
    'Émirats Arabes Unis',
    'Espagne',
    'États-Unis',
    'Finlande',
    'France',
    'Grèce',
    'Inde',
    'Irlande',
    'Italie',
    'Japon',
    'Luxembourg',
    'Maroc',
    'Mexique',
    'Norvège',
    'Nouvelle-Zélande',
    'Pays-Bas',
    'Pologne',
    'Portugal',
    'Qatar',
    'Royaume-Uni',
    'Russie',
    'Singapour',
    'Suède',
    'Suisse',
    'Tunisie',
    'Turquie'
];